# Use postgres/example user/password credentials
version: '3.3'
services:
    postgres:
        container_name: postgres_drf
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: 'drf_user'
            POSTGRES_PASSWORD: 'drf_password'
            POSTGRES_DB: 'drf_db'
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata